name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

permissions:
  contents: write  # Required for creating releases

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build executable
      run: |
        python build_exe.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rov-autoconnect-exe
        path: dist/ROV_AutoConnect.exe
        retention-days: 1
  
  release:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: rov-autoconnect-exe
        path: dist
      
    - name: Create Release
      run: |
        if gh release view ${{ github.ref_name }} >/dev/null 2>&1; then
          echo "Release ${{ github.ref_name }} already exists, skipping creation"
        else
          gh release create ${{ github.ref_name }} \
            --title "ROV Auto-Connect v${{ github.ref_name }}" \
            --notes "## ROV Auto-Connect v${{ github.ref_name }}

### What's New
- Automated ROV stream discovery and connection
- Built-in VLC integration for video streaming
- Modern, user-friendly interface

### Installation
1. Download the executable from this release
2. Ensure VLC Media Player is installed on your system
3. Run the executable and click \"Connect to ROV Stream\"

### Requirements
- Windows 10/11
- VLC Media Player (download from https://www.videolan.org/vlc/)
- Network connection to ROV" \
            --draft=false \
            --prerelease=false
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Upload Release Asset
      run: |
        gh release upload ${{ github.ref_name }} dist/ROV_AutoConnect.exe --clobber
        echo "Release asset uploaded successfully"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 